### ISSUE TITLE
What do pos_feature and neg_feature in the source code mean?

### ISSUE THREAD

**Issue by YongtaoGE** [Snowball-Wang/LFW_accuracy_test#1]
Hi, @Snowball-Wang.  what is the order of the feature in the lmdb file? Does it the same order as the "pairs.txt"?

**Comment by Snowball-Wang** [comment]
@geyongtao sorry for replying so late. No, the order of the feature in the lmdb file is **different from** the order in "pairs.txt". In the original "pairs.txt", it has 10 groups of pos pairs and neg pairs, which totally accounts for 12000 images. But I rearrage the order of 12000 images into the file "LFW_pairs_imagelist.txt". The first 6000 images are photos of pos pairs and the rest are neg pairs. So when I convert the image into lmdb file,  the first 6000 feature vectors are positive, the rest are negative.
that's why you will see the following code in src file:
```
pos_feature = feature_list[:6000] 
neg_feature = feature_list[6000:120000]
```
And by the way, the reason I do this is for the convenience of 10-fold evaluation in the next step.
Hope my reply helps.

**Comment by YongtaoGE** [comment]
@Snowball-Wang It really helps. Thanks a lot!
